name: payu_state_management
description: Flutter package with Payu interface which allows to use wrapper over state management.
version: 1.0.2
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.3 <4.10.0'
  flutter: ">=3.22.2"
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  payu_interface:
    git:
      url: https://github.com/rmasarovic/PayU-Flutter
      path: payu_interface
  payu_ui:
    git:
      url: https://github.com/rmasarovic/PayU-Flutter
      path: payu_ui
  provider: ^6.0.3
dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter:
