name: payu_terms_and_conditions
description: Flutter package with Payu Terms and Conditions widget
version: 1.0.2
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.3 <4.10.0'
  flutter: ">=3.22.2"
dependencies:
  flutter:
    sdk: flutter
  payu_core:
    git:
      url: https://github.com/rmasarovic/PayU-Flutter
      path: payu_core
  payu_state_management:
    git:
      url: https://github.com/rmasarovic/PayU-Flutter
      path: payu_state_management
  payu_translations:
    git:
      url: https://github.com/rmasarovic/PayU-Flutter
      path: payu_translations
  payu_ui:
    git:
      url: https://github.com/rmasarovic/PayU-Flutter
      path: payu_ui
dev_dependencies:
  build_runner: ^2.4.8
  dependency_validator: ^3.2.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
flutter:
