name: payu_core
description: Flutter package with Payu core functionality and models.
version: 1.0.2
publish_to: none
homepage: https://github.com/PayU-EMEA/PayU-Flutter
issue_tracker: https://github.com/PayU-EMEA/PayU-Flutter/issues
environment:
  sdk: '>=3.4.3 <4.10.0'
  flutter: ">=3.22.2"
dependencies:
  flutter:
    sdk: flutter
  payu_interface:
    git:
      url: https://github.com/rmasarovic/PayU-Flutter
      path: payu_interface
  url_launcher: ^6.1.6
dev_dependencies:
  build_runner: ^2.4.8
  dependency_validator: ^3.2.2
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter:
